### ISSUE TITLE
run formulator error

### ISSUE THREAD

**Issue by Booyoun-Kim** [meverselabs/meverse#1]
```
$ ./formulator
panic: Cannot write pid file "/home/ubuntu/fleta/cmd/formulator/formulator/LOCK": open /home/ubuntu/fleta/cmd/formulator/formulator/LOCK: not a directory

goroutine 1 [running]:
main.main()
	/home/ubuntu/fleta/cmd/formulator/main.go:128 +0x1957
```

My go version is go version go1.12.7 linux/amd64.

**Comment by judasowelu** [comment]
Fixed.
The problem is default StoreRoot setting of config.toml that has same with execution file.

https://github.com/fletaio/fleta/commit/3a4503c1bf276e22efb42588ead8cfe7a425860a
