### ISSUE TITLE
fleta/cmd/formulator/fdata permissions error

### ISSUE THREAD

**Issue by gojun077** [meverselabs/meverse#2]
Hello~

After cloning the fleta repo and running `go build` in `fleta/cmd/node`, incorrect permissions are set on the directory `fleta/cmd/formulator/fdata`... fdata for some reason has permssions of `000`, when it should have permissions of 755 `rwxr-xr-x`. I had to manually fix this with `chmod -R 755 fdata`.

After changing the permissions I could finally run `./formulator` without any errors. Do you know why `fdata` folder is being created with such weird permissions?

-Jun

**Comment by judasowelu** [comment]
Issue resolved by followed commit.
We change creation permission to ModePerm instead of ModeDir

https://github.com/fletaio/fleta/commit/530d41b0988132dab548ed79bdb885d07fdd26f0
